import type { Metadata } from "next";

export const metadata: Metadata = {
  alternates: {
    canonical: '/scientific-calculator/',
  },
  title: "Scientific Calculator | Trigonometric & Logarithmic Math",
  description:
    "Solve advanced STEM equations online. Execute trigonometry operations, calculate logarithms, and process exponents with strict order of operations. Including specialized USA tools like scientific calculator, ti 84 plus ce, graphing calculator.",
  keywords: [
    "scientific calculator",
    "ti 84 plus ce",
    "graphing calculator",
    "ti 84 calculator",
    "ti 84",
    "casio calculator",
    "dti calculator",
    "ti 84 plus",
    "casio fx cg50",
    "ti 84 graphing calculator",
    "mathpapa",
    "ti 30x iis",
    "ti 84 plus ce t",
    "ti 83",
    "casio scientific calculator",
    "ti 30xiis",
    "ti 30xs",
    "ti nspire cx",
    "ti nspire",
    "adding machine",
    "ti nspire cx ii",
    "ti 36x pro",
    "ti 83 calculator",
    "ti calculator",
    "ti nspire cx cas",
    "ti 30xa",
    "ti 89",
    "ti 83 plus",
    "ti 84 calculator online",
    "graphing calculator online",
    "scientific notation calculator",
    "scientific calculator online",
    "desmos graphing calculator",
    "scientific calculator app",
    "scientific calculator price",
    "casio calculator online",
    "ti 84 online",
    "casio calculator price",
    "ti connect ce",
    "graphing",
    "mathpapa algebra calculator",
    "desmos scientific calculator",
    "mathpapa calculator",
    "3d graphing calculator",
    "desmos graphing",
    "desmos scientific",
    "geogebra graphing",
    "geogebra graphing calculator",
    "calculator app",
    "math calculator",
    "math solver online",
    "payroll deductions online calculator",
    "equation solver",
    "maths solver",
    "math equation solver",
    "math solver with steps",
    "math calculator with steps",
    "algebra solver",
    "microsoft math solver",
    "equation calculator",
    "free calculator",
    "linear equation calculator",
    "simultaneous equations solver",
    "quadratic equation solver",
    "quadratic equation calculator",
    "photomath pc",
    "simultaneous equations calculator",
    "quadratic solver",
    "matrix solver",
    "integral solver",
    "age calculator app",
    "desmos calculator",
    "density equation",
    "desmos 3d",
    "desmos com",
    "harris benedict equation",
    "calculator",
    "tax calculator",
    "annuity calculator",
    "tax return calculator",
    "tax refund estimator",
    "bra size calculator",
    "concrete calculator",
    "finance calculator",
    "tax calculator 2023",
    "tax estimator 2023",
    "tax calculator 2022",
    "tax estimator",
    "tax return estimate",
    "savings calculator",
    "algebra calculator",
    "freight class calculator",
    "tax estimator 2022",
    "budget calculator",
    "free tax calculator",
    "bond calculator",
    "refund calculator",
    "paint calculator",
    "roofing calculator",
    "irs tax calculator",
    "federal tax calculator",
    "2022 tax calculator",
    "savings account calculator",
    "hr block tax calculator",
    "shipping calculator",
    "apr calculator",
    "mulch calculator",
    "amazon fba calculator",
    "line of credit calculator",
    "2023 tax refund calculator",
    "home calculator",
    "annuity payout calculator",
    "2022 tax refund calculator",
    "tax withholding calculator",
    "gpa",
    "asphalt calculator",
    "h and r block tax calculator",
    "2023 tax calculator",
    "tax refund calculator 2022 2023",
    "h&r block calculator",
    "bra calculator",
    "construction calculator",
    "ltv calculator",
    "credit card calculator",
    "geometry calculator",
    "w4 calculator",
    "commission calculator",
    "tax return calculator 2022",
    "texas instruments calculator",
    "cement calculator",
    "tax bracket calculator",
    "roof pitch calculator",
    "irs calculator",
    "s&p 500 calculator",
    "federal tax withholding calculator",
    "forex calculator",
    "federal withholding calculator",
    "tax refund calculator 2022",
    "net worth calculator",
    "depreciation calculator",
    "benefits calculator",
    "withholding calculator",
    "tax deduction calculator",
    "agi calculator",
    "statistics calculator",
    "irr calculator",
    "return calculator",
    "state tax calculator",
    "financial calculator online",
    "annuity formula",
    "calculus calculator",
    "rental property calculator",
    "inverse function calculator",
    "property tax calculator",
    "topsoil calculator",
    "inequality calculator",
    "soil calculator",
    "algebra calculator with steps",
    "i bond calculator",
    "imc calculator",
    "life expectancy calculator",
    "gravel calculator",
    "calculator online",
    "carb calculator",
    "texas instruments ba ii plus",
    "scrap gold calculator",
    "domain and range calculator",
    "water intake calculator",
    "weekly tax calculator",
    "present value of annuity calculator",
    "cable size calculator",
    "online tax calculator",
    "future value calculator",
    "currency calculator",
    "future value of annuity calculator",
    "2021 tax calculator",
    "money calculator",
    "integral calculator",
    "google calculator",
    "net pay calculator",
    "radical calculator",
    "trigonometry calculator",
    "domain calculator",
    "polynomial calculator",
    "hp prime",
    "postal life insurance calculator",
    "golf handicap calculator",
    "profit calculator",
    "inverse calculator",
    "interval notation calculator",
    "basic calculator",
    "simple tax calculator",
    "electricity cost calculator",
    "aggregate calculator",
    "water calculator",
    "rmr calculator",
    "stair calculator",
    "advanced calculator",
    "algebraic expression calculator",
    "hp calculator",
    "work calculator",
    "npv calculator",
    "net present value calculator",
    "resistor calculator",
    "bond price calculator",
    "taxi calculator",
    "samsung calculator",
    "simple calculator",
    "tax calculator 2021",
    "conduit fill calculator",
    "brick calculator",
    "calculator please",
    "function calculator",
    "kwh calculator",
    "tax credit calculator",
    "synthetic division calculator",
    "handicap calculator",
    "electricity calculator",
    "long division calculator",
    "chemistry calculator",
    "land transfer tax calculator",
    "energy calculator",
    "kcal calculator",
    "price calculator",
    "piecewise function calculator",
    "expression calculator",
    "cas calculator",
    "dividing polynomials calculator",
    "pemdas calculator",
    "distributive property calculator",
    "ebay shipping calculator",
    "ohms law calculator",
    "non programmable calculator",
    "power consumption calculator",
    "trig calculator",
    "smart calculator",
    "calculator with steps",
    "engineering calculator",
    "lottery calculator",
    "integers calculator",
    "military pay calculator",
    "derivative calculator",
    "present value of annuity",
    "calculator with solution",
    "linear programming calculator",
    "fire calculator",
    "programmable calculator",
    "augmented matrix calculator",
    "variable calculator",
    "wire size calculator",
    "parallel resistor calculator",
    "slope calculator",
    "simplifying calculator",
    "army pay calculator",
    "reverse tax calculator",
    "ibm calculator",
    "t value calculator",
    "paye tax calculator",
    "grading calculator",
    "simplification calculator",
    "power calculator",
    "quadratic formula",
    "watts to amps calculator",
    "median calculator",
    "mechanical calculator",
    "fuel consumption calculator",
    "future value of annuity",
    "dilution calculator",
    "calculator online free",
    "definite integral calculator",
    "bonus tax calculator",
    "pv calculator",
    "lottery tax calculator",
    "final exam calculator",
    "fuel economy calculator",
    "sand calculator",
    "gear ratio calculator",
    "mpg calculator",
    "black scholes calculator",
    "standard form calculator",
    "torque calculator",
    "integration by parts calculator",
    "vo2 max calculator",
    "clock calculator",
    "land calculator",
    "wacc calculator",
    "substitution calculator",
    "aspect ratio",
    "measurement calculator",
    "complex number calculator",
    "rref calculator",
    "stair stringer calculator",
    "find the median",
    "amp calculator",
    "arithmetic sequence calculator",
    "dividend tax calculator",
    "harris benedict calculator",
    "expected value calculator",
    "height calculator",
    "simplest form calculator",
    "biorhythm calculator",
    "exponential function calculator",
    "polynomial long division calculator",
    "find x calculator",
    "geometric sequence calculator",
    "curta",
    "division calculator",
    "common denominator calculator",
    "apr formula",
    "open calculator",
    "integral calculator with steps",
    "aspect ratio calculator",
    "law of sines calculator",
    "calculator net",
    "ppm calculator",
    "decimal calculator",
    "quadratic calculator",
    "point slope form calculator",
    "pro rata calculator",
    "root calculator",
    "ratio calculator",
    "differentiation calculator",
    "curta calculator",
    "difference quotient calculator",
    "find the quotient",
    "pi calculator",
    "implicit differentiation calculator",
    "running calculator",
    "quadratic function calculator",
    "face shape calculator",
    "tvm calculator",
    "the calculator",
    "partial derivative calculator",
    "vertex form calculator",
    "derivative calculator with steps",
    "cash calculator",
    "golden ratio face calculator",
    "composite function calculator",
    "fourier series calculator",
    "paye calculator 2022",
    "future value",
    "vertex calculator",
    "x intercept calculator",
    "series calculator",
    "laplace transform calculator",
    "bonus calculator",
    "cube root calculator",
    "vector calculator",
    "critical value calculator",
    "frequency calculator",
    "sin calculator",
    "xirr calculator",
    "law of cosines calculator",
    "student finance calculator",
    "purchasing power calculator",
    "maintenance calculator",
    "ffmi calculator",
    "density calculator",
    "double integral calculator",
    "parabola calculator",
    "rounding calculator",
    "big number calculator",
    "solar powered calculators",
    "significant figures calculator",
    "cumulative gpa calculator",
    "degree calculator",
    "ibw calculator",
    "cos calculator",
    "m2 calculator",
    "limits calculator",
    "nth term calculator",
    "laplace calculator",
    "chain rule calculator",
    "geometric series calculator",
    "rsd calculator",
    "haversine formula",
    "discriminant calculator",
    "elden ring level calculator",
    "pivot point calculator",
    "gauss jordan calculator",
    "range calculator",
    "eigenvalue calculator",
    "present value formula",
    "increase calculator",
    "3 significant figures",
    "a gpa",
    "b gpa",
    "binomial expansion calculator",
    "bsa calculator",
    "bsa formula",
    "c to f calculator",
    "c to f formula",
    "calculator site",
    "change calculator",
    "change formula",
    "checksum calculator",
    "circumference calculator",
    "cola calculator",
    "convergence calculator",
    "coterminal angle calculator",
    "critical point calculator",
    "cumulative gpa",
    "current calculator",
    "data calculator",
    "delusion calculator",
    "density formula",
    "difference calculator",
    "duration calculator",
    "exam calculator",
    "fibonacci calculator",
    "final calculator",
    "future value formula",
    "gate calculator",
    "golden ratio calculator",
    "google calculator online",
    "gp calculator",
    "gpa scale",
    "gradient calculator",
    "gram schmidt calculator",
    "half life calculator",
    "harris benedict formula",
    "hcf calculator",
    "horsepower calculator",
    "hyperbola calculator",
    "interval of convergence calculator",
    "inverse matrix calculator",
    "log2 calculator",
    "maclaurin series calculator",
    "mass calculator",
    "maturity value",
    "minute calculator",
    "mode calculator",
    "modulo calculator",
    "ohm's law formula",
    "outlier calculator",
    "payback period formula",
    "power series calculator",
    "ppi calculator",
    "ppm formula",
    "present value",
    "price increase calculator",
    "profitability index formula",
    "projectile motion calculator",
    "pv formula",
    "quartile calculator",
    "ratio test calculator",
    "reduced echelon form calculator",
    "reduced row echelon form calculator",
    "resolution calculator",
    "rok calculator",
    "row echelon form calculator",
    "row reduction calculator",
    "rust raid calculator",
    "scale calculator",
    "series convergence calculator",
    "sin inverse calculator",
    "slope formula",
  ],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
