import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Salary Calculator",
  description:
    "Convert your salary instantly. Find out your hourly, daily, weekly, monthly, and annual equivalent pay rates for any income. Including specialized USA tools like income tax calculator, salary calculator, paycheck calculator.",
  keywords: [
    "income tax calculator",
    "salary calculator",
    "paycheck calculator",
    "debt to income ratio calculator",
    "federal income tax calculator",
    "paycheck tax calculator",
    "hourly to salary calculator",
    "debt to income ratio",
    "federal income tax rate calculator",
    "annual income calculator",
    "income tax calculator 2022",
    "annual salary calculator",
    "free paycheck calculator",
    "taxable income calculator",
    "income calculator",
    "hourly wage calculator",
    "yearly income calculator",
    "yearly salary calculator",
    "monthly income calculator",
    "salary tax calculator",
    "calculate my paycheck",
    "hourly paycheck calculator",
    "paycheck city",
    "monthly salary calculator",
    "hourly rate to salary",
    "net income calculator",
    "wages calculator",
    "after tax income calculator",
    "gross income calculator",
    "salary paycheck calculator",
    "salary converter",
    "2021 income tax calculator",
    "take home salary calculator",
    "smartasset paycheck calculator",
    "net salary calculator",
    "adp hourly paycheck calculator",
    "gross monthly income calculator",
    "salary increase calculator",
    "salary after tax",
    "salary after tax calculator",
    "pro rata salary calculator",
    "take home pay calculator",
    "hourly rate calculator",
    "hourly pay calculator",
    "pay rate calculator",
    "work out take home pay",
    "take home calculator",
    "take home pay",
    "adp hourly calculator",
    "gross pay calculator",
    "gross margin calculator",
    "gross to net",
    "gross to net calculator",
    "net to gross calculator",
    "gross profit calculator",
  ],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
