import { Metadata } from "next";

export const metadata: Metadata = {
  alternates: {
    canonical: '/mortgage-calculator/',
  },
  title: "Mortgage Calculator",
  description:
    "Calculate your monthly mortgage payments precisely. Our free mortgage calculator includes principal, interest, property taxes, home insurance, and HOA fees. Including specialized USA tools like mortgage calculator, reverse mortgage calculator, mortgage payment calculator.",
  keywords: [
    "mortgage calculator",
    "reverse mortgage calculator",
    "mortgage payment calculator",
    "cash out refinance calculator",
    "va mortgage calculator",
    "mortgage repayment calculator",
    "mortgage loan calculator",
    "simple mortgage calculator",
    "refinance mortgage calculator",
    "buy to let mortgage calculator",
    "home mortgage calculator",
    "closing cost calculator",
    "mortgage estimator",
    "mortgage rate calculator",
    "bankrate mortgage calculator",
    "monthly mortgage calculator",
    "commercial mortgage calculator",
    "free mortgage calculator",
    "interest only mortgage calculator",
    "house mortgage calculator",
    "estimate mortgage payment",
    "mortgage calculator with taxes",
    "car refinance calculator",
    "mortgage qualification calculator",
    "mortgage insurance calculator",
    "monthly mortgage payment calculator",
    "google mortgage calculator",
    "mortgage amortization calculator",
    "30 year mortgage calculator",
    "mortgage calculator how much can i borrow",
    "online mortgage calculator",
    "mortgage interest calculator",
    "debt to income ratio for mortgage",
    "quick mortgage calculator",
    "mortgage payment",
    "mortgage calculator with taxes and insurance",
    "mortgage amortization schedule",
    "mortgage calculator with extra payments",
    "early mortgage payoff calculator",
    "home loan calculator",
    "home equity loan calculator",
    "va loan calculator",
    "va home loan calculator",
    "heloc payment calculator",
    "home loan repayment calculator",
    "equity loan calculator",
    "equity calculator",
    "home loan interest calculator",
    "chase home value estimator",
    "home loan interest rate calculator",
    "kva to amps",
    "house payment calculator",
    "house calculator",
    "pmi calculator",
  ],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
